name: AppPack Upload Artifacts
description: Upload build artifacts to S3
branding:
  icon: box
  color: purple
inputs:
  appname:
    description: Name of the AppPack app
    required: true
outputs:
  artifacts_bucket:
    description: S3 Bucket for artifacts
  artifacts_prefix:
    description: S3 prefix (path) for artifacts

runs:
  using: node16
  main: index.js
